
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Description: Vagrantfile for Ansible
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure("2") do |config|


  config.vm.define "redis_server" do |server|
    config.vm.box = "centos/7"
    # Specify the Vagrant box to use
    server.vm.box = "centos/7"
    # Specify the VM ip address
    config.vm.network "forwarded_port", guest: 80, host: 8080
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "redis.server.local"
      # VM RAM in MB
      vb.memory = 2048
      # VM CPUs
      vb.cpus = 1
    end
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "2048"
    vmware.vmx["numvcpus"] = "1"
  end
end

  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end

end
