---
- name: Check redis --health
  uri:
    url: http://localhost:6379/health
    status_code: 200
    return_content: yes
  register: redis_health
  retries: 5
  delay: 10
  until: redis_health.status == 200
  tags: healthchecks
