version: "3"
services:
  redis:
    image: redis
  web:
    # COMPLETE HERE
    build: .
    ports:
      - "5000:3000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis